### ISSUE TITLE
Need room capacity for reservations

### ISSUE THREAD

**Issue by maxnabokow** [unc-csxl/csxl.unc.edu#616] opened 2024-09-16 01:37 UTC
Currently, the room reservation system only shows when which room is booked, not how many people fit in it.
Ideally, each room should show how many it can seat. Or at least what it's called (e.g. "Team room" or "Pair Programming room").

**Comment by ajaygandecha** [comment] 2024-09-16 01:42
Currently in progress (#599), bumping this @kiernan-a and @ellieekimm

(Closing since duplicate of #599)

**Closed** 2024-09-16 01:42 UTC
